repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^.github/

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^.github/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      exclude: ^.github/
