name: Deploy conda packages (wip)

on:
  workflow_dispatch:

jobs:
  build:
    name: deploy on ${{ matrix.os }} using python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'potassco/conda'
        ref: 'master'

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: build
        channels: potassco,potassco/label/dev

    - name: install prerequisites
      shell: pwsh
      run: conda install conda-build anaconda-client


    - name: print info
      shell: pwsh
      run: |
        conda info
        conda list

    - name: publish conda package
      shell: pwsh
      run: |
        Set-Location "python-clingox"
        python upload.py
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
