name: tests

on:
  - push
  - pull_request

jobs:
  build:
    name: clingox ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2

    - name: setup miniconda
      uses: goanpeca/setup-miniconda@v1.1.2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: clingox
        channels: potassco/label/dev,conda-forge

    - name: install prerequisites
      shell: pwsh
      run: conda install clingo clingo-dl clingcon

    - name: info
      shell: pwsh
      run: |
        conda info
        conda list
        python --version

    - name: test
      shell: pwsh
      run: python -m unittest discover
